### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by dodas** [prisma/prisma-cloud-feedback#222]
Hi,
folowing issue [#3240 on prisma/prisma](https://github.com/prisma/prisma/issues/3240#issuecomment-427787928), I am re-submitting my issue.

After few deploys, I can't deploy again.
Prisma CLI output:
```
ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjnafippe00340971xysl9vrr

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjnafippe00340971xysl9vrr",
      "path": [
        "deploy"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "local:management:cjnafippe00340971xysl9vrr"
    }
  ],
  "status": 200
}
```

heroku run bash -a appName:
```
Oct 15, 2018 3:01:38 PM org.postgresql.Driver connect
SEVERE: Connection error:
org.postgresql.util.PSQLException: FATAL: permission denied for database "postgres"
  Detail: User does not have CONNECT privilege.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Obtaining exclusive agent lock...
Initializing workers...
Successfully started 1 workers.
Server running on :44181
Version is up to date.
```

Cheers.

**Comment by nfuad** [comment]
This is a real issue.

**Comment by mishkinf** [comment]
I am getting the same issue

**Comment by dodas** [comment]
I was getting error while having both Prisma server and database on heroku.

**Comment by prajjwaldimri** [comment]
Still getting this error on Prisma 1.24

**Comment by divyenduz** [comment]
Are you using Prisma cloud to deploy to Heroku or using Heroku with Prisma docker image directly?

**Comment by Andre153** [comment]
I had this issue for a while. I resolved it by resetting my heroku database with

heroku pg:reset

you can also set access rules on the database for the user

**Comment by BaoPham92** [comment]
I am also having this problem.

> I had this issue for a while. I resolved it by resetting my heroku database with
> 
> heroku pg:reset
> 
> you can also set access rules on the database for the user

I also tried this method reseting the pq database, still the same FATAL error warning.

**Comment by ngaruko** [comment]
`docker restart` worked for me
