### ISSUE TITLE
Large Seeds

### ISSUE THREAD

**Issue by mikedklein** [prisma/prisma-cloud-feedback#248]
When trying use a large seed it looks like the API operation times out and gives and E2BIG error. 

Which in and of itself is reasonable because this is a huge seed. But the unexpected behavior is that it does seed partially so then I end up with it partially done.

I have confirmed entering the seed into the playground and it working, it just obviously is cumbersome.

Also, to note I am doing this on a heroku DB instance that can support this many rows.

Any information is appreciated.

```
Error: spawn E2BIG
    at ChildProcess.spawn (internal/child_process.js:372:11)
    at Object.spawn (child_process.js:544:9)
    at StatusChecker.checkStatus (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/src/StatusChecker.ts:94:5)
    at Output.<anonymous> (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/src/Output/index.ts:203:21)
    at step (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Output/index.js:43:23)
    at Object.next (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Output/index.js:24:53)
    at /Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Output/index.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Output/index.js:14:12)
    at Output.error (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Output/index.js:216:16)
    at Function.<anonymous> (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/src/Command.ts:70:15)
    at step (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Command.js:32:23)
    at Object.throw (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Command.js:13:53)
    at rejected (/Users/mike.klein/development/corelegal/corelegal-backend/node_modules/prisma-cli-engine/dist/Command.js:5:65)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  util timed out +0ms
Exiting with code: 0
```

**Comment by mikedklein** [comment]
As a follow up I wasn't sure if this was a prisma cloud or just prisma issue but it seemed to be prisma cloud from what I could guess.
